# Generated by Django 4.0.5 on 2022-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cart',
            field=models.JSONField(null=True),
        ),
    ]
