# Generated by Django 4.0.5 on 2022-06-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_useraccount_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='cart',
        ),
    ]
