# Generated by Django 4.0.5 on 2022-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_remove_useraccount_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cart',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='review_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
