# Generated by Django 4.0.5 on 2022-06-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_remove_useraccount_review_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='cart',
        ),
    ]
