# Generated by Django 4.0.5 on 2022-06-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_remove_useraccount_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='staff',
            field=models.BooleanField(null=True),
        ),
    ]
