# Generated by Django 4.0.5 on 2022-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
