# Generated by Django 4.0.5 on 2022-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_alter_book_author_name_alter_book_cover_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_art',
            field=models.TextField(null=True),
        ),
    ]
