# Generated by Django 4.0.5 on 2022-06-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0004_alter_book_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
