# Generated by Django 4.0.5 on 2022-06-16 01:48

import books_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0005_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name=books_api.models.Book)),
                ('user', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
