# Generated by Django 4.0.5 on 2022-06-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0007_book_reviews_alter_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(to='books_api.review'),
        ),
    ]
