# Generated by Django 4.0.5 on 2022-06-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0008_remove_book_reviews_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(null=True, to='books_api.review'),
        ),
    ]
