# Generated by Django 4.0.5 on 2022-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0011_remove_book_reviews_book_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
