# Generated by Django 4.0.5 on 2022-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0012_remove_review_user_review_book_id_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
