# Generated by Django 4.0.5 on 2022-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0013_alter_review_book_id_alter_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
