# Generated by Django 4.0.5 on 2022-06-17 03:21

import books_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0014_alter_review_book_id_alter_review_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.JSONField(null=True, verbose_name=books_api.models.Review),
        ),
    ]
