# Generated by Django 4.0.5 on 2022-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0019_alter_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='books_api.review'),
        ),
    ]
